services:
  mongo:
    image: mongo:8
    container_name: healthcare_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo-init:/docker-entrypoint-initdb.d:ro

  migrator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: healthcare_migrator
    depends_on:
      - mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}
      MONGO_COLLECTION: ${MONGO_COLLECTION}
    volumes:
      - ../data:/app/data
      - ../reports:/app/reports
      - ../src:/app/src
    command: ["python", "src/migrate_validate.py"]

volumes:
  mongo_data: